set(SCSA_ANALYSIS_PRO 	"analysis")
set(SCSA_CORE_PRO		"core")
set(SCSA_NETWORK_PRO 	"network")
set(SCSA_SERVICE_PRO 	"service")

set(SCSA_SERVER_DIR		"Server")

set(SCSA_PROJECT_001	"${SC_PROJECT_SA_SERVER_001}")

set(SCSA_SERVER_DEPS "${SCSA_SERVICE_PRO}")

set(SCSA_DEPENDENCY_LIST "")
list(APPEND SCSA_DEPENDENCY_LIST "${SCSA_PROJECT_001}:${SCSA_SERVER_DEPS}")

set(SCSA_PROJECT_DIR_LIST "")
list(APPEND SCSA_PROJECT_DIR_LIST "${SCSA_PROJECT_001}:${SCSA_SERVER_DIR}/${SCSA_PROJECT_001}")

function(scsa_get_dependencies PROJECT_NAME DEPENDENCY_LIST_VAR)
	sc_get_flatmp_value(${PROJECT_NAME} TEMP_VAR ${SCSA_DEPENDENCY_LIST})
	set(${DEPENDENCY_LIST_VAR} "${TEMP_VAR},core" PARENT_SCOPE)
endfunction()

function(scsa_get_project_dir PROJECT_NAME PROJECT_DIR_VAR)
	sc_get_flatmp_value(${PROJECT_NAME} TEMP_VAR ${SCSA_PROJECT_DIR_LIST})
	set(${PROJECT_DIR_VAR} "${TEMP_VAR}" PARENT_SCOPE)
endfunction()