set(SC_PROJECT_SA "ScSignalAnalysis")
set(SC_PROJECT_SA_SERVER_001 "ScServer")

set(SC_PROJECT_DIR_LIST "")
list(APPEND SC_PROJECT_DIR_LIST "${SC_PROJECT_SA_SERVER_001}:${SC_PROJECT_SA}")

function(sc_get_flatmp_value KEY VALUE_VAR)
	set(${VALUE_VAR} "" PARENT_SCOPE)
	set(RETURN_LIST "")
    foreach(ELEMENT_PAIR ${ARGN})
        STRING(REGEX REPLACE "([^:]+):.*" "\\1" KEY_RESULT ${ELEMENT_PAIR})
        if(${KEY_RESULT} STREQUAL ${KEY} )
            STRING(REGEX REPLACE "[^:]+:(.*)" "\\1" VALUE_RESULT ${ELEMENT_PAIR})
            list(APPEND RETURN_LIST "${VALUE_RESULT}")
        endif()
    endforeach()
	set(${VALUE_VAR} "${RETURN_LIST}" PARENT_SCOPE)
endfunction()

function(sc_get_project_dir PROJECT_NAME PROJECT_DIR)
    sc_get_flatmp_value(${PROJECT_NAME} TEMP_VAR ${SC_PROJECT_DIR_LIST})
    set(${PROJECT_DIR} "${TEMP_VAR}" PARENT_SCOPE)
endfunction()

function(sc_get_all_keys KEY_LIST_VAR)  
   set(${KEY_LIST_VAR} "" PARENT_SCOPE)  
   set(RETURN_KEYS "")  
   foreach(ELEMENT_PAIR ${SC_PROJECT_DIR_LIST})  
       STRING(REGEX REPLACE "([^:]+):.*" "\\1" KEY_RESULT ${ELEMENT_PAIR})  
       list(APPEND RETURN_KEYS "${KEY_RESULT}")  
   endforeach()  
   set(${KEY_LIST_VAR} "${RETURN_KEYS}" PARENT_SCOPE)  
endfunction()